import { Poppins } from "next/font/google";
// import "./globals.css";
import Navbar from "@/Components/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/Components/Footer";

const inter = Poppins({ subsets: ["latin"], weight: ["400" ,"500","700","900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
